--
-- PostgreSQL database dump
--

\restrict TX38Uc4bZuNGnvPbL9I7roEneooGi4C8LhQWDVCxfFScWTpqqAJk5NaSgE88Nz5

-- Dumped from database version 14.19
-- Dumped by pg_dump version 14.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: sahibinden_db; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA sahibinden_db;


ALTER SCHEMA sahibinden_db OWNER TO postgres;

--
-- Name: students; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA students;


ALTER SCHEMA students OWNER TO postgres;

--
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: brands; Type: TABLE; Schema: sahibinden_db; Owner: postgres
--

CREATE TABLE sahibinden_db.brands (
    id integer NOT NULL,
    name character varying(255)
);


ALTER TABLE sahibinden_db.brands OWNER TO postgres;

--
-- Name: brands_id_seq; Type: SEQUENCE; Schema: sahibinden_db; Owner: postgres
--

ALTER TABLE sahibinden_db.brands ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sahibinden_db.brands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cars; Type: TABLE; Schema: sahibinden_db; Owner: postgres
--

CREATE TABLE sahibinden_db.cars (
    brand_id integer NOT NULL,
    id integer NOT NULL,
    km integer,
    price double precision,
    year integer,
    color character varying(255),
    model character varying(255)
);


ALTER TABLE sahibinden_db.cars OWNER TO postgres;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: sahibinden_db; Owner: postgres
--

ALTER TABLE sahibinden_db.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sahibinden_db.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: sahibinden_db; Owner: postgres
--

CREATE TABLE sahibinden_db.users (
    id integer NOT NULL,
    email character varying(255),
    password character varying(255),
    user_name character varying(255)
);


ALTER TABLE sahibinden_db.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: sahibinden_db; Owner: postgres
--

ALTER TABLE sahibinden_db.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sahibinden_db.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: students; Owner: postgres
--

CREATE TABLE students.student (
    id integer NOT NULL,
    birth_of_date timestamp(6) without time zone,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL
);


ALTER TABLE students.student OWNER TO postgres;

--
-- Name: student_id_seq; Type: SEQUENCE; Schema: students; Owner: postgres
--

ALTER TABLE students.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME students.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: brands; Type: TABLE DATA; Schema: sahibinden_db; Owner: postgres
--

COPY sahibinden_db.brands (id, name) FROM stdin;
1	BMW
2	Mercedes
3	TOGG
4	TOFAS
5	TOYOTA
\.


--
-- Data for Name: cars; Type: TABLE DATA; Schema: sahibinden_db; Owner: postgres
--

COPY sahibinden_db.cars (brand_id, id, km, price, year, color, model) FROM stdin;
2	1	10000	80000	2011	RED	XX
3	2	10000	80000	2011	BLACK	AA
3	3	10000	80000	2011	BLACK	BB
1	4	10000	80000	2011	GREY	TB
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: sahibinden_db; Owner: postgres
--

COPY sahibinden_db.users (id, email, password, user_name) FROM stdin;
\.


--
-- Data for Name: student; Type: TABLE DATA; Schema: students; Owner: postgres
--

COPY students.student (id, birth_of_date, first_name, last_name) FROM stdin;
1	2004-06-27 03:00:00	tuba	eraslan
\.


--
-- Name: brands_id_seq; Type: SEQUENCE SET; Schema: sahibinden_db; Owner: postgres
--

SELECT pg_catalog.setval('sahibinden_db.brands_id_seq', 5, true);


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: sahibinden_db; Owner: postgres
--

SELECT pg_catalog.setval('sahibinden_db.cars_id_seq', 4, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: sahibinden_db; Owner: postgres
--

SELECT pg_catalog.setval('sahibinden_db.users_id_seq', 1, false);


--
-- Name: student_id_seq; Type: SEQUENCE SET; Schema: students; Owner: postgres
--

SELECT pg_catalog.setval('students.student_id_seq', 1, true);


--
-- Name: brands brands_pkey; Type: CONSTRAINT; Schema: sahibinden_db; Owner: postgres
--

ALTER TABLE ONLY sahibinden_db.brands
    ADD CONSTRAINT brands_pkey PRIMARY KEY (id);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: sahibinden_db; Owner: postgres
--

ALTER TABLE ONLY sahibinden_db.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: sahibinden_db; Owner: postgres
--

ALTER TABLE ONLY sahibinden_db.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: students; Owner: postgres
--

ALTER TABLE ONLY students.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- Name: cars fk864li48nqoslem704ihv4ax3a; Type: FK CONSTRAINT; Schema: sahibinden_db; Owner: postgres
--

ALTER TABLE ONLY sahibinden_db.cars
    ADD CONSTRAINT fk864li48nqoslem704ihv4ax3a FOREIGN KEY (brand_id) REFERENCES sahibinden_db.brands(id);


--
-- PostgreSQL database dump complete
--

\unrestrict TX38Uc4bZuNGnvPbL9I7roEneooGi4C8LhQWDVCxfFScWTpqqAJk5NaSgE88Nz5

